# Generated by Django 5.2.1 on 2025-05-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_agegroup_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='age_groups',
            field=models.ManyToManyField(blank=True, related_name='games', to='wiki.agegroup'),
        ),
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='games', to='wiki.tag'),
        ),
    ]
