# Generated by Django 5.2.1 on 2025-05-24 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_game_downvote_count_game_upvote_count_vote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='downvote_count',
        ),
        migrations.RemoveField(
            model_name='game',
            name='upvote_count',
        ),
        migrations.RemoveField(
            model_name='game',
            name='votes',
        ),
        migrations.AlterField(
            model_name='vote',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='wiki.game'),
        ),
    ]
