# Generated by Django 5.2.1 on 2025-05-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_remove_game_downvote_count_remove_game_upvote_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default="2025-05-26T13:47:03Z"),
            preserve_default=False,
        ),
    ]
